format = """
[░▒▓](#73ba25)\
[  ](bg:#73ba25 fg:#000000)\
[](bg:#475a5f fg:#73ba25)\
$directory\
[](fg:#475a5f bg:#35b9ab)\
$git_branch\
$git_status\
[](fg:#35b9ab bg:#212736)\
$python\
$container\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#475a5f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "
"Sources" = "󰮮"
"~" = ":"

[git_branch]
symbol = ""
style = "bg:#35b9ab"
format = '[[ $symbol $branch ](fg:#000000 bg:#35b9ab)]($style)'

[git_status]
style = "bg:#35b9ab"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#35b9ab)]($style)'

[python]
symbol= ""
# Updated to official Python Yellow
style = "fg:#FFD43B bg:#212736"
format = '[\[$symbol $virtualenv\]]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#35b9ab bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#35b9ab bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#35b9ab bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#35b9ab bg:#212736)]($style)'

[container]
symbol = ""
format = "[$symbol $name]($style)"
style = "bold #35b9ab"

[time]
disabled = false
time_format = "%R" 
style = "bg:#1d2230"
format = '[[  $time ](fg:#73ba25 bg:#1d2230)]($style)'

[character]
success_symbol = "[❯](bold #73ba25)"
error_symbol = "[❯](bold #f44336)"
vimcmd_symbol = "[❮](bold #35b9ab)"
